# Generated by Django 4.2.6 on 2023-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioimg', models.FileField(upload_to='static/projectimg')),
                ('p_title', models.CharField(max_length=15)),
                ('p_name', models.CharField(max_length=20)),
                ('p_url', models.SlugField(verbose_name='static/projecturls')),
                ('p_catagry', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='addservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=20)),
                ('service_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='addvideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(upload_to='static/myvideos')),
                ('v_title', models.CharField(max_length=15)),
                ('v_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
