# Generated by Django 4.2.6 on 2023-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_myrevies'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_img', models.FileField(upload_to='static/blogimg')),
                ('B_catagry', models.TextField(max_length=50)),
                ('B_description', models.TextField(max_length=150)),
                ('B_subheading', models.TextField(max_length=50)),
            ],
        ),
    ]
